# Recommendation System Notebook
- User based recommendation
- User based prediction & evaluation
- Item based recommendation
- Item based prediction & evaluation

Different Approaches to develop Recommendation System -

1. Demographich based Recommendation System

2. Content Based Recommendation System

3. Collaborative filtering Recommendation System

In [21]:
# import libraties
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import DataFrame

In [22]:
# Reading ratings file from GitHub. # MovieLens
ratings = pd.read_csv('sample30.csv' , encoding='latin-1')
ratings.head()
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    30000 non-null  object
 1   brand                 30000 non-null  object
 2   categories            30000 non-null  object
 3   manufacturer          29859 non-null  object
 4   name                  30000 non-null  object
 5   reviews_date          29954 non-null  object
 6   reviews_didPurchase   15932 non-null  object
 7   reviews_doRecommend   27430 non-null  object
 8   reviews_rating        30000 non-null  int64 
 9   reviews_text          30000 non-null  object
 10  reviews_title         29810 non-null  object
 11  reviews_userCity      1929 non-null   object
 12  reviews_userProvince  170 non-null    object
 13  reviews_username      29937 non-null  object
 14  user_sentiment        29999 non-null  object
dtypes: int64(1), object(14)
memory usage

## Dividing the dataset into train and test

In [23]:
# Test and Train split of the dataset.
from sklearn.model_selection import train_test_split
train, test = train_test_split(ratings, test_size=0.30, random_state=31)

In [24]:
print(train.shape)
print(test.shape)

(21000, 15)
(9000, 15)


In [25]:
# Pivot the train ratings' dataset into matrix format in which columns are movies and the rows are user IDs.

#df = train.groupby(by=['reviews_username', 'id', 'reviews_rating']).first()

df_redup = train.drop_duplicates(subset=['reviews_username', 'id'], keep='last')






print(df_redup.info())





<class 'pandas.core.frame.DataFrame'>
Int64Index: 19767 entries, 11155 to 21202
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   id                    19767 non-null  object
 1   brand                 19767 non-null  object
 2   categories            19767 non-null  object
 3   manufacturer          19666 non-null  object
 4   name                  19767 non-null  object
 5   reviews_date          19734 non-null  object
 6   reviews_didPurchase   10598 non-null  object
 7   reviews_doRecommend   18178 non-null  object
 8   reviews_rating        19767 non-null  int64 
 9   reviews_text          19767 non-null  object
 10  reviews_title         19640 non-null  object
 11  reviews_userCity      1141 non-null   object
 12  reviews_userProvince  97 non-null     object
 13  reviews_username      19753 non-null  object
 14  user_sentiment        19767 non-null  object
dtypes: int64(1), object(14)
memory u

### Creating dummy train & dummy test dataset
These dataset will be used for prediction 
- Dummy train will be used later for prediction of the movies which has not been rated by the user. To ignore the movies rated by the user, we will mark it as 0 during prediction. The movies not rated by user is marked as 1 for prediction in dummy train dataset. 

- Dummy test will be used for evaluation. To evaluate, we will only make prediction on the movies rated by the user. So, this is marked as 1. This is just opposite of dummy_train.

In [26]:


df_pivot = df_redup.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(0)

df_pivot.head(10)


id                         AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                                        
NaN                                         0.0                   0.0   
00dog3                                      0.0                   0.0   
00sab00                                     0.0                   0.0   
01impala                                    0.0                   0.0   
0325home                                    0.0                   0.0   
06stidriver                                 0.0                   0.0   
09mommy11                                   0.0                   0.0   
1085                                        0.0                   0.0   
10ten                                       0.0                   0.0   
11111111aaaaaaaaaaaaaaaaa                   0.0                   0.0   

id                         AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                                        
NaN                                         0.0                   0.0   
00dog3                                      0.0                   0.0   
00sab00                                     0.0                   0.0   
01impala                                    0.0                   0.0   
0325home                                    0.0                   0.0   
06stidriver                                 0.0                   0.0   
09mommy11                                   0.0                   0.0   
1085                                        0.0                   0.0   
10ten                                       0.0                   0.0   
11111111aaaaaaaaaaaaaaaaa                   0.0                   0.0   

id                         AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                                        
NaN                                         0.0                   0.0   
00dog3                                      0.0                   0.0   
00sab00                                     0.0                   0.0   
01impala                                    0.0                   0.0   
0325home                                    0.0                   0.0   
06stidriver                                 0.0                   0.0   
09mommy11                                   0.0                   0.0   
1085                                        0.0                   0.0   
10ten                                       0.0                   0.0   
11111111aaaaaaaaaaaaaaaaa                   0.0                   0.0   

id                         AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                                        
NaN                                         0.0                   0.0   
00dog3                                      0.0                   0.0   
00sab00                                     0.0                   0.0   
01impala                                    0.0                   0.0   
0325home                                    0.0                   0.0   
06stidriver                                 0.0                   0.0   
09mommy11                                   0.0                   0.0   
1085                                        0.0                   0.0   
10ten                                       0.0                   1.0   
11111111aaaaaaaaaaaaaaaaa                   0.0                   0.0   

id                         AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                                       ...   
NaN                                         0.0                   0.0  ...   
00dog3                                      0.0                   0.0  ...   
00sab00                                     0.0                   0.0  ...   
01impala                                    0.0                   0.0  ...   
0325home                

In [27]:
# Copy the train dataset into dummy_train
dummy_train = train.copy()

In [28]:
dummy_train.head()

id          brand  \
11155  AVpf3VOfilAPnD_xjpun         Clorox   
22114  AVpf--o9LJeJML43G_Fq       Vaseline   
26218  AVpfPkrkilAPnD_xX-L9         Finish   
18966  AVpfJP1C1cnluZ0-e3Xy         Clorox   
29999  AVpfW8y_LJeJML437ySW  L'oreal Paris   

                                              categories       manufacturer  \
11155  Household Essentials,Cleaning Supplies,Kitchen...             Clorox   
22114  Personal Care,Skin Care,Hand Cream,Beauty,Body...           Vaseline   
26218  Household Essentials,Cleaning Supplies,Dish De...  Reckitt Benckiser   
18966  Household Chemicals,Household Cleaners,Bath & ...     AmazonUs/CLOO7   
29999  Beauty,Hair Care,Shampoo & Conditioner,Holiday...      L'oreal Paris   

                                                    name  \
11155  Clorox Disinfecting Wipes Value Pack Scented 1...   
22114  Vaseline Intensive Care Healthy Hands Stronger...   
26218  Finish Gelpacs Dishwasher Detergent, Orange Sc...   
18966               Clorox Disinfecting Bathroom Cleaner   
29999  L'or233al Paris Elvive Extraordinary Clay Reba...   

                   reviews_date reviews_didPurchase reviews_doRecommend  \
11155  2015-01-05T00:00:00.000Z               False                True   
22114  2016-03-19T00:00:00.000Z               False                True   
26218  2013-04-25T16:51:02.000Z                 NaN                True   
18966  2012-01-21T00:00:00.000Z               False                True   
29999  2017-01-19T00:00:00.000Z               False                True   

       reviews_rating                                       reviews_text  \
11155               5  It's quick and easy compared to using a spray ...   
22114               4  Stronger nails after a week of daily use. Not ...   
26218               5  REALLY DOES CLEAN EVERYTHING AND SO GOOD ON GL...   
18966               5  These wipes are great for cleaning in the kitc...   
29999               5  I received this product complimentary from inf...   

                  reviews_title reviews_userCity reviews_userProvince  \
11155              Clorox wipes              NaN                  NaN   
22114         VERY GOOD PRODUCT              NaN                  NaN   
26218                 Excellent              NaN                  NaN   
18966  Great wipes, great smell              NaN                  NaN   
29999  Conditioned into healthy              NaN                  NaN   

      reviews_username user_sentiment  
11155         gor05751       Positive  
22114          annavsl       Positive  
26218         bluenose       Positive  
18966             kiki       Positive  
29999        kcoopxoxo       Positive

In [29]:
# The movies not rated by user is marked as 1 for prediction. 
dummy_train['reviews_rating'] = dummy_train['reviews_rating'].apply(lambda x: 0 if x>=1 else 1)

In [30]:
# Convert the dummy train dataset into matrix format.
dummy_train_redup = dummy_train.drop_duplicates(subset=['reviews_username', 'id'], keep='last')
dummy_train = dummy_train_redup.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
).fillna(1)

In [31]:
dummy_train.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
NaN                                1.0                   1.0  ...   
00dog3                             1.0                   1.0  ...   
00sab00                            1.0                   1.0  ...   
01impala                           1.0                   1.0  ...   
0325home                           1.0                   1.0  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AVpfrgjFLJeJML43BvCc  AVpfs0tUilAPnD_xgqN2  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0                   1.0   
0325home                           1.0                   1.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
NaN                                1.0                   1.0   
00dog3                             1.0                   1.0   
00sab00                            1.0                   1.0   
01impala                           1.0               

**Cosine Similarity**

Cosine Similarity is a measurement that quantifies the similarity between two vectors [Which is Rating Vector in this case] 

**Adjusted Cosine**

Adjusted cosine similarity is a modified version of vector-based similarity where we incorporate the fact that different users have different ratings schemes. In other words, some users might rate items highly in general, and others might give items lower ratings as a preference. To handle this nature from rating given by user , we subtract average ratings for each user from each user's rating for different movies.



# User Similarity Matrix

## Using Cosine Similarity

In [32]:
df_pivot.index.nunique()

18252

In [33]:
from sklearn.metrics.pairwise import pairwise_distances

# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_pivot, metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1.         0.         0.         ... 0.24854791 0.24854791 0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.24854791 0.         0.         ... 1.         1.         0.        ]
 [0.24854791 0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [34]:
user_correlation.shape

(18253, 18253)

## Using adjusted Cosine 

### Here, we are not removing the NaN values and calculating the mean only for the movies rated by the user

In [35]:
# Create a user-movie matrix.
df_redup = train.drop_duplicates(subset=['reviews_username', 'id'], keep='last')
df_pivot = df_redup.pivot(
    index='reviews_username',
    columns='id',
    values='reviews_rating'
)

In [36]:
df_pivot.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
NaN                                NaN                   NaN  ...   
00dog3                             NaN                   NaN  ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
0325home                           NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfs0tUilAPnD_xgqN2  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN               

### Normalising the rating of the movie for each user around 0 mean

In [37]:
mean = np.nanmean(df_pivot, axis=1)
df_subtracted = (df_pivot.T-mean).T

In [38]:
df_subtracted.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
NaN                                NaN                   NaN  ...   
00dog3                             NaN                   NaN  ...   
00sab00                            NaN                   NaN  ...   
01impala                           NaN                   NaN  ...   
0325home                           NaN                   NaN  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfrgjFLJeJML43BvCc  AVpfs0tUilAPnD_xgqN2  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN                   NaN   
0325home                           NaN                   NaN   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
NaN                                NaN                   NaN   
00dog3                             NaN                   NaN   
00sab00                            NaN                   NaN   
01impala                           NaN               

### Finding cosine similarity

In [39]:
from sklearn.metrics.pairwise import pairwise_distances

In [40]:
# Creating the User Similarity Matrix using pairwise_distance function.
user_correlation = 1 - pairwise_distances(df_subtracted.fillna(0), metric='cosine')
user_correlation[np.isnan(user_correlation)] = 0
print(user_correlation)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [41]:
user_correlation.shape

(18253, 18253)

## Prediction - User User

Doing the prediction for the users which are positively related with other users, and not the users which are negatively related as we are interested in the users which are more similar to the current users. So, ignoring the correlation for values less than 0. 

In [42]:
user_correlation[user_correlation<0]=0
user_correlation

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Rating predicted by the user (for movies rated as well as not rated) is the weighted sum of correlation with the movie rating (as present in the rating dataset). 

In [43]:
user_predicted_ratings = np.dot(user_correlation, df_pivot.fillna(0))
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
user_predicted_ratings.shape

(18253, 252)

In [45]:
user_predicted_ratings

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Since we are interested only in the movies not rated by the user, we will ignore the movies rated by the user by making it zero. 

In [46]:
user_final_rating = np.multiply(user_predicted_ratings,dummy_train)
user_final_rating.head()

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
NaN                                0.0              0.138056   
00dog3                             0.0              0.000000   
00sab00                            0.0              0.000000   
01impala                           0.0              0.000000   
0325home                           0.0              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
NaN                                0.0                   0.0  ...   
00dog3                             0.0                   0.0  ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   
0325home                           0.0                   0.0  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
NaN                            0.18263                   0.0   
00dog3                         0.00000                   0.0   
00sab00                        0.00000                   0.0   
01impala                       0.00000                   0.0   
0325home                       0.00000                   0.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfrgjFLJeJML43BvCc  AVpfs0tUilAPnD_xgqN2  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   

id                AVpfthSailAPnD_xg3ON  AVpftikC1cnluZ0-p31V  \
reviews_username                                               
NaN                           0.056194                   0.0   
00dog3                        0.000000                   0.0   
00sab00                       0.000000                   0.0   
01impala                      0.000000               

### Finding the top 5 recommendation for the *user*

In [47]:
# Take the user ID as input.
user_input = input("Enter your user name")
print(user_input)

Enter your user name0325home
0325home


In [48]:
user_final_rating.head(7)

id                AV13O1A8GV-KLJ3akUyj  AV14LG0R-jtxr-f38QfS  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
09mommy11                          0.0                   0.0   

id                AV16khLE-jtxr-f38VFn  AV1YGDqsGV-KLJ3adc-O  \
reviews_username                                               
NaN                                0.0              0.138056   
00dog3                             0.0              0.000000   
00sab00                            0.0              0.000000   
01impala                           0.0              0.000000   
0325home                           0.0              0.000000   
06stidriver                        0.0              0.000000   
09mommy11                          0.0              0.000000   

id                AV1YIch7GV-KLJ3addeG  AV1YlENIglJLPUi8IHsX  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
09mommy11                          0.0                   0.0   

id                AV1YmBrdGV-KLJ3adewb  AV1YmDL9vKc47QAVgr7_  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0                   0.0   
09mommy11                          0.0                   0.0   

id                AV1Ymf_rglJLPUi8II2v  AV1Yn94nvKc47QAVgtst  ...  \
reviews_username                                              ...   
NaN                                0.0                   0.0  ...   
00dog3                             0.0                   0.0  ...   
00sab00                            0.0                   0.0  ...   
01impala                           0.0                   0.0  ...   
0325home                           0.0                   0.0  ...   
06stidriver                        0.0                   0.0  ...   
09mommy11                          0.0                   0.0  ...   

id                AVpfr5cb1cnluZ0-pZFp  AVpfrFDZLJeJML43Bmv0  \
reviews_username                                               
NaN                            0.18263                   0.0   
00dog3                         0.00000                   0.0   
00sab00                        0.00000                   0.0   
01impala                       0.00000                   0.0   
0325home                       0.00000                   0.0   
06stidriver                    0.00000                   0.0   
09mommy11                      0.00000                   0.0   

id                AVpfrTyiLJeJML43BrSI  AVpfrfHF1cnluZ0-pRai  \
reviews_username                                               
NaN                                0.0                   0.0   
00dog3                             0.0                   0.0   
00sab00                            0.0                   0.0   
01impala                           0.0                   0.0   
0325home                           0.0                   0.0   
06stidriver                        0.0       

In [49]:
print(type(user_final_rating))

<class 'pandas.core.frame.DataFrame'>


In [50]:
d = user_final_rating.loc[user_input].sort_values(ascending=False)[0:5]
d

id
AVpfvieo1cnluZ0-qdnu    0.0
AVpf-k78LJeJML43G4qN    0.0
AVpf3okQLJeJML43FMif    0.0
AVpf3VOfilAPnD_xjpun    0.0
AVpf385g1cnluZ0-s0_t    0.0
Name: 0325home, dtype: float64

In [ ]:
#taking into a pikle file 

pd.to_pickle(d, "model/recomendationlookupfile.pkl")